### ISSUE TITLE
How does this compare

### ISSUE THREAD

**Issue by migig** [nbouvrette/eventListenerPolyfill#1]
To [MDN's polyfill](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Compatibility), which has been the standard polyfill for some time?

**Comment by nbouvrette** [comment]
End result is probably fairly similar. On the other hand if you are looking for something very specific (one time event), I would suggest that you take a look at the code at the bottom of this example:

https://github.com/nbouvrette/svgfallback/blob/master/svgfallback.js

Originally I was planning to use this Polyfill for that use case but found that for one-offs, that format is much simpler and requires less overhead that loading a complete Polyfill.

**Comment by nbouvrette** [comment]
By the way I just noted that MDN's polyfill seems to have issues with IE edge in IE8 emulator mode. It's throwing errors on listener in some cases while a real IE8 will behave correctly. This polyfill seems to avoid those issues.
